const routes = {
  home: "/",
  providers: "/providers",
  tienda: "/tienda",
  sobre_nosotros: "/sobre-nosotros",
  soporte: "/soporte",
  login: "/login",
  editar_perfil: "/editar-perfil",
  forgotPassword: "/recuperar-contraseña",
  register: "/registro",
  dashboard: "/dashboard",
  logout: "/logout",
  clientes: "/clientes",
  infoUsuario: "/info-usuario",
  ventas: "/ventas",
  plataformas: "/plataformas",
  plataformasClientes: "/plataformas-clientes",
  solicitudesPlataformas: "/solicitud-plataforma",
};
export default routes;
